version: "3.9"
services:
  # Backend API
  api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/bin/smart-brain-api

    # For development purposes: syncs changes between local dir
    # and docker container filesystem
    # volumes:
    #   - ./:/usr/bin/smart-brain-api

    environment:
      POSTGRES_URI: postgres://admin:password@postgres:5432/smart-brain
      REDIS_URI: redis://redis:6379
    ports:
      - "3000:3000"

  # Postgres
  postgres:
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smart-brain
      POSTGRES_HOST: postgres
      POSTGRES_URL: postgres://admin:password@localhost:5432/smart-brain
    build: ./postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"
